ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.example.noteapi.ApplicationKt.module ]
    }
}
jwt {
    domain = "https://jwt-provider-domain/"
    audience = "jwt-audience"
    realm = "note-api"
    secret = "secret-key-for-development-only"
}
database {
    jdbcUrl = "jdbc:postgresql://localhost:5432/notedb"
    jdbcUrl = ${?DB_URL}
    driverClassName = "org.postgresql.Driver"
    username = "postgres"
    username = ${?DB_USER}
    password = "password"
    password = ${?DB_PASSWORD}
}
